parameters:
  eye_on_hand: false
  freehand_robot_movement: false
  move_group: panda_arm
  move_group_namespace: panda
  namespace: /panda_eob_calib_eye_on_base/
  robot_base_frame: panda_link0
  robot_effector_frame: panda_link7
  tracking_base_frame: camera_bottom_screw_frame
  tracking_marker_frame: aruco_marker_frame
transformation:
  qw: 0.05991596292219753
  qx: -0.33601319271965563
  qy: 0.07858823810092253
  qz: 0.9366584759332734
  x: 1.444245120901501
  y: -0.4275731112964708
  z: 0.8437504149116686
